name: Create release
on:
  pull_request_target:
    branches:
      - main
    types:
      - closed
jobs:
  release:
    if: github.event.pull_request.merged == true && !contains(github.event.pull_request.title, 'skip-release')
    uses: libops/.github/.github/workflows/bump-release.yaml@3bdb895c3fd05490b0c6a1341e630ac554842468 # main
    permissions:
      contents: write
      actions: write
