name: Create release
on:
  pull_request_target:
    branches:
      - main
    types:
      - closed
jobs:
  release:
    if: github.event.pull_request.merged == true && !contains(github.event.pull_request.title, 'skip-release')
    uses: libops/actions/.github/workflows/bump-release.yaml@main
    permissions:
      contents: write
      actions: write
    secrets: inherit

