name: Lint and Test

on:
  push:

jobs:
  lint-test:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Install terraform-docs
        run: |
          curl -sSLo ./terraform-docs.tar.gz https://terraform-docs.io/dl/v0.20.0/terraform-docs-v0.20.0-$(uname)-amd64.tar.gz
          tar -xzf terraform-docs.tar.gz
          chmod +x terraform-docs
          sudo mv terraform-docs /usr/local/bin/terraform-docs

      - name: Terraform Format Check
        run: terraform fmt -check -recursive .

      - name: Generate Documentation
        run: make docs

      - name: Check for Documentation Changes
        run: |
          if ! git diff --exit-code README.md; then
            echo "❌ Documentation is out of date. Please run 'make docs' and commit the changes."
            exit 1
          else
            echo "✅ Documentation is up to date."
          fi

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate
